CREATE USER IF NOT EXISTS 'bugs'@'%' IDENTIFIED BY 'bugs';
GRANT REPLICATION SLAVE, REPLICATION CLIENT, SUPER ON *.* TO 'bugs'@'%';
FLUSH PRIVILEGES;


USE bugs;

CREATE TABLE IF NOT EXISTS random_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  value VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);