until mysql -h"$MASTER_HOST" -P"$MASTER_PORT" -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW MASTER STATUS\G"; do
  echo "Waiting for master to be ready..."
  sleep 5
done

MASTER_LOG_FILE=$(mysql -h"$MASTER_HOST" -P"$MASTER_PORT" -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW MASTER STATUS\G" | grep File | awk '{print $2}')
MASTER_LOG_POS=$(mysql -h"$MASTER_HOST" -P"$MASTER_PORT" -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW MASTER STATUS\G" | grep Position | awk '{print $2}')

echo "MASTER_LOG_FILE: $MASTER_LOG_FILE"
echo "MASTER_LOG_POS: $MASTER_LOG_POS"

mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CHANGE MASTER TO MASTER_HOST='$MASTER_HOST', MASTER_USER='$MYSQL_USER', MASTER_PASSWORD='$MYSQL_PASSWORD', MASTER_LOG_FILE='$MASTER_LOG_FILE', MASTER_LOG_POS=$MASTER_LOG_POS; START SLAVE;"
